import Head from 'next/head'
import Image from 'next/image'

import Header from '../../components/Header'

import proyectosList from '../../content/proyectos.json'

const Proyecto = ({ data }) => {

    const imageSizes = [
        {
            height: 1172,
            width: 1920
        },
        {
            height: 867,
            width: 1920
        },
        {
            height: 1133,
            width: 1280
        },
        {
            height: 350,
            width: 350
        },
        {
            height: 1173,
            width: 1920
        }
    ]
    
    return(
        <>
            <Head>
                <title>Proyecto { data.nombre }, Agencia digital y creativa</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <section className="proyecto__banner site-banner fondo-banner-proyecto pt-4">
                <div className="site-banner-inner center">
                    <Header />
                    <div className="site__banner-copy site__banner-proyecto-copy">
                        <figure className="site__banner-bg-image">
                            <Image 
                                alt={ data.heroTitle }
                                src={ data.heroImg }
                                layout="fill"
                                objectFit="cover"
                                priority
                            />
                        </figure>
                        <h2 className="site__banner-image-copy">{ data.heroTitle }</h2>
                    </div>
                </div>
            </section>
            <main>
                <div className="proyecto__concepto">
                    <div className="ancho-80 center flex flex-flow-row col-gap-2 pt-4">
                        <div className="proyecto__state proyecto__state-description ancho-50">
                            <h2 className="proyecto__titulo">
                                <span className="proyecto__titulo-numero">01</span>
                                <span className="proyecto__titulo-texto"><strong>Concepto</strong><br /> de la marca</span>
                            </h2>
                            <div className="text-container" dangerouslySetInnerHTML={{ __html: data.concepto }} />
                        </div>
                        <div className="proyecto__state-image ancho-50">
                            <figure className="proyecto__logo-concepto">
                                <Image 
                                    alt={ data.heroTitle }
                                    src={ data.conceptoLogo }
                                    layout="intrinsic"
                                    height={ 700 }
                                    width={ 700 }
                                />
                            </figure>
                        </div>
                    </div>
                    <figure className="proyecto__image-ancho-full">
                        <Image 
                            alt={ data.heroTitle }
                            src={ data.conceptoBanner }
                            layout="intrinsic"
                            height={ 1063 }
                            width={ 1920  }
                        />
                    </figure>
                </div>
                <div className="proyecto__cta-image">
                    <Image 
                        alt={ data.heroTitle }
                        src={ data.marcaCTA }
                        layout="fill"
                        objectFit="cover"
                    />
                </div>
                <div className="proyecto__post-cta">
                    <Image 
                        alt={ data.heroTitle }
                        src={ data.imgPostCTA }
                        layout="intrinsic"
                        height={ 1177 }
                        width={ 1920  }
                    />
                </div>
                <div className="proyecto__construccion">
                    <div className="ancho-80 center">
                        <div className="proyecto__state proyecto__state-description ancho-50">
                            <h2 className="proyecto__titulo">
                                <span className="proyecto__titulo-numero">02</span>
                                <span className="proyecto__titulo-texto"><strong>Construcción</strong><br /> de la marca</span>
                            </h2>
                        </div>
                    </div>
                    <div className="proyecto__construccion-wrap">
                        <Image 
                            alt={ data.heroTitle }
                            src={ data.construccionMarca }
                            layout="intrinsic"
                            height={ 504 }
                            width={ 1280  }
                        />
                    </div>
                    <div className="proyecto__proceso">
                        <Image 
                            alt={ data.heroTitle }
                            src={ data.construccionImagen }
                            layout="intrinsic"
                            height={ 1003 }
                            width={ 1920  }
                        />
                    </div>
                    <div className="proyecto__simbolo">
                        <div className="pt-4 flex flex-flow-row justify-space-between">
                            <figure className="proyecto__simbolo-img ancho-50 center">
                                <Image 
                                    alt={ data.heroTitle }
                                    src={ data.simbolo }
                                    layout="intrinsic"
                                    height={ 300 }
                                    width={ 229 }
                                />
                            </figure>
                            <div className="ancho-50 flex align-items-center">
                                <div className="text-container" dangerouslySetInnerHTML={{ __html: data.textoSimbolo }} />
                            </div>
                        </div>
                        <div className="proyecto__bocetos">
                            <Image
                                alt={ data.heroTitle }
                                src={ data.bocetos }
                                layout="intrinsic"
                                height={ 1146 }
                                width={ 1920 }
                            />
                        </div>
                    </div>
                </div>
                <div className="proyecto__implementacion">
                    <div className="ancho-80 center flex flex-flow-row col-gap-2">
                        <div className="proyecto__state proyecto__state-description ancho-50">
                            <h2 className="proyecto__titulo">
                                <span className="proyecto__titulo-numero">03</span>
                                <span className="proyecto__titulo-texto"><strong>Implementación</strong><br /> de la marca</span>
                            </h2>
                        </div>
                    </div>
                    <div className="proyecto__implementacion-gallery ancho-80 center">
                        {
                            data.implementacion.map( ( img, index ) => (
                                <div key={ index } className={`proyecto__image-${ index }`}>
                                    <Image
                                        alt={ data.heroTitle }
                                        src={ img }
                                        layout="intrinsic"
                                        height={ imageSizes[index].height }
                                        width={ imageSizes[index].width }
                                    />
                                </div>
                            ) )
                        }
                    </div>
                </div>
            </main>
        </>
    )
}

export const getStaticPaths = ({ locales }) => {

    let paths = []
    
    proyectosList.map( proyecto => {
        
        locales.map( locale => {

            paths.push({

                params:{
                    nombre: proyecto.nombre
                },
                locale

            })

        })

    })

    return{
        paths,
        fallback: false
    }

}

export const getStaticProps = ({ locale, params }) => {

    const data = proyectosList.find( proyecto => proyecto.nombre == params.nombre )

    return{
        props:{
            data
        }
    }

}

export default Proyecto